' SPDX-FileCopyrightText: Copyright 2022-2023 Arm Limited and/or its affiliates <open-source-office@arm.com>
' SPDX-License-Identifier: CC-BY-SA-4.0 AND LicenseRef-Patent-license

@startuml

'' State diagram
!include atg-spec.pumh

skinparam LegendFontSize 12

legend
  **Transitions**
  <color:blue>--""———""--</color> Applies to a single component
  <color:darkred>--""———""--</color> Applies to all components

  **Volatile states**
  "" † "" Optional: **reboot** is equivalent to ""cancel"" and ""clean""
  "" ‡ "" Optional: **reboot** is equivalent to ""clean""
end legend

state Start as "READY"
state Writing as "WRITING †"
state Candidate as "CANDIDATE"
state Failed as "FAILED ‡"
state Updated as "UPDATED ‡"
state End as "READY"

Start -[#blue]-> Writing : ""start""
Writing -[#blue]-> Writing : ""write""
Writing -[#blue]-> Candidate : ""finish""
Writing -[#blue]-> Failed : ""cancel""
Candidate -[#darkred]-> Updated : ""install"":\n//install success//
Candidate -r[#blue]-> Failed : ""cancel""

Failed -u[#blue]-> Start: ""clean""

Updated -r[#blue]-> End : ""clean""

@enduml
