' SPDX-FileCopyrightText: Copyright 2023 Arm Limited and/or its affiliates <open-source-office@arm.com>
' SPDX-License-Identifier: CC-BY-SA-4.0 AND LicenseRef-Patent-license

@startuml

'' State diagram
!include atg-spec.pumh

skinparam LegendFontSize 12

legend bottom
  <color:blue>--""———""--</color> Blue transitions apply to a single component
  <color:darkred>--""———""--</color> Red transitions apply to all components
  ""---"" Dashed lines indicate a transition over **reboot**
  "" * "" Transient state: transitions at **reboot**
  "" † "" Transient state: **reboot** is equivalent to ""cancel"" and ""clean""
  "" ‡ "" Transient state: **reboot** is equivalent to ""clean""
end legend

state Start as "READY"
state Writing as "WRITING †"
state Candidate as "CANDIDATE †"
state Staged as "STAGED *"
state Failed as "FAILED ‡"
state End as "READY"

Start -[#blue]-> Writing : ""start""
Writing -[#blue]-> Writing : ""write""
Writing -[#blue]-> Candidate : ""finish""
Writing -[#blue]-> Failed : ""cancel""
Candidate -r[#blue]-> Failed : ""cancel""
Candidate -d[#darkred]-> Staged : ""install""

Staged -[#darkred,dashed]-> End : ""reboot"":\n//install success//
Staged -u[#darkred,dashed]-> Start : ""reboot"":\n//install failed//
Staged -u[#darkred]-> Failed : ""reject""

Failed -u[#blue]-> Start: ""clean""

@enduml
