' SPDX-FileCopyrightText: Copyright 2023 Arm Limited and/or its affiliates <open-source-office@arm.com>
' SPDX-License-Identifier: CC-BY-SA-4.0 AND LicenseRef-Patent-license

@startuml

'' State diagram
!include atg-spec.pumh

skinparam LegendFontSize 12

legend
  **Transitions**
  <color:blue>--""———""--</color> Applies to a single component
  <color:darkred>--""———""--</color> Applies to all components
  ""---"" Transition over **reboot**

  **Volatile states**
  "" * "" Always: **reboot** transition as shown
  "" † "" Always: **reboot** is equivalent to ""cancel"" and ""clean""
  "" ‡ "" Always: **reboot** is equivalent to ""clean""
end legend

state Start as "READY"
state Writing as "WRITING †"
state Candidate as "CANDIDATE †"
state Staged as "STAGED *"
state Failed as "FAILED ‡"
state End as "READY"

Start -[#blue]-> Writing : ""start""
Writing -[#blue]-> Writing : ""write""
Writing -[#blue]-> Candidate : ""finish""
Writing -[#blue]-> Failed : ""cancel""
Candidate -r[#blue]-> Failed : ""cancel""
Candidate -[#darkred]-> Staged : ""install""

Staged -r[#darkred,dashed]-> End : **reboot**:\n//install success//
Staged -u[#darkred,dashed]-> Start : **reboot**:\n//install failed//
Staged -u[#darkred]-> Failed : ""reject""

Failed -u[#blue]-> Start: ""clean""

@enduml
