' SPDX-FileCopyrightText: Copyright 2023 Arm Limited and/or its affiliates <open-source-office@arm.com>
' SPDX-License-Identifier: CC-BY-SA-4.0 AND LicenseRef-Patent-license

@startuml

' State diagram
!include atg-spec.pumh

skinparam LegendFontSize 12

legend
  **Transitions**
  <color:blue>--""———""--</color> Applies to a single component
  <color:darkred>--""———""--</color> Applies to all components
  ""---"" Transition over **reboot**

  **Volatile states**
  "" * "" Always: **reboot** transition as shown
  "" † "" Always: **reboot** is equivalent to ""cancel"" and ""clean""
  "" ‡ "" Always: **reboot** is equivalent to ""clean""
end legend

state Start as "READY"
state Writing as "WRITING †"
state Candidate as "CANDIDATE †"
state Staged as "STAGED *"
state Failed as "FAILED ‡"
state Rejected as "REJECTED *"
state Trial as "TRIAL *"
state Updated as "UPDATED ‡"
state End as "READY"

Start -[#blue]-> Writing : ""start""
Writing -[#blue]-> Writing : ""write""
Writing -[#blue]-> Candidate : ""finish""
Writing -[#blue]-> Failed : ""cancel""
Candidate -[#darkred]-> Staged : ""install""
Candidate -r[#blue]-> Failed : ""cancel""

Staged -r[#darkred,dashed]-> Trial : **reboot**:\n//install success//
Staged -[#darkred,dashed]-> Start : **reboot**:\n//install failed//
Staged -u[#darkred]-> Failed : ""reject""

Trial -[#darkred]-> Updated : ""accept""

Failed -u[#blue]-> Start: ""clean""
Trial -r[#darkred]-> Rejected : ""reject""
Rejected -[#darkred,dashed,norank]-> Start : **reboot**:\n//rollback//

Trial -[#darkred,dashed,norank]-> Start : **reboot**:\n//rollback//

Updated -r[#blue]-> End : ""clean""

@enduml
