' SPDX-FileCopyrightText: Copyright 2022 Arm Limited and/or its affiliates
' SPDX-License-Identifier: CC-BY-SA-4.0 AND LicenseRef-Patent-license

@startuml
!include psa-spec.pumh

skinparam defaultTextAlignment center

interface "Crypto API" as api
rectangle Application as app
rectangle Cryptoprocessor as crypto

app -> api: call
api - crypto

@enduml
