' SPDX-FileCopyrightText: Copyright 2022-2023 Arm Limited and/or its affiliates <open-source-office@arm.com>
' SPDX-License-Identifier: CC-BY-SA-4.0 AND LicenseRef-Patent-license

@startuml

' State diagram
!include atg-spec.pumh

skinparam LegendFontSize 12

legend bottom
  <color:blue>--""———""--</color> Blue transitions apply to a single component
  <color:darkred>--""———""--</color> Red transitions apply to all components
  ""---"" Dashed lines indicate a transition over **reboot**
  "" * "" Transient state: transitions at **reboot**
end legend

state Start as "READY"
state Writing as "WRITING"
state Candidate as "CANDIDATE"
state Staged as "STAGED *"
state Failed as "FAILED"
state Rejected as "REJECTED *"
state Trial as "TRIAL *"
state Updated as "UPDATED"
state End as "READY"

Start -[#blue]-> Writing : ""start""
Writing -[#blue]-> Writing : ""write""
Writing -[#blue]-> Candidate : ""finish""
Writing -d[#blue]-> Failed : ""cancel""
Candidate -[#darkred]-> Staged : ""install""
Candidate -r[#blue]-> Failed : ""cancel""

Staged -[#darkred,dashed]-> Trial : ""reboot"":\n//install success//
Staged -u[#darkred,dashed]-> Failed : ""reboot"":\n//install failed//
Staged -u[#darkred]-> Failed : ""reject""

Trial -[#darkred]-> Updated : ""accept""

Failed -u[#blue]-> Start: ""clean""
Trial -u[#darkred]-> Rejected : ""reject""
Rejected -u[#darkred,dashed]-> Failed : ""reboot"":\n//rollback//

Trial -[#darkred,dashed,norank]-> Failed : ""reboot"":\n//rollback//

Updated -[#blue]-> End : ""clean""

@enduml
