# SPDX-FileCopyrightText: Copyright 2022, 2024 Arm Limited and/or its affiliates <open-source-office@arm.com>
# SPDX-License-Identifier: CC-BY-SA-4.0

title: PSA Certified APIs
description: The official place for the latest published documents of the PSA Certified APIs
logo: assets/img/Arm_logo_blue_RGB.svg

domain: arm-software.github.io
url: "https://arm-software.github.io"
baseurl: /psa-api/

theme: jekyll-theme-minimal

include: [_static, _images]

source: site-src
destination: docs

github:
  repository_url: "https://github.com/ARM-software/psa-api"
  repository_nwo: "ARM-software/psa-api"
  owner_url: "https://github.com/ARM-software"
  owner_name: "ARM-software"
