' SPDX-FileCopyrightText: Copyright 2023 Arm Limited and/or its affiliates
' SPDX-License-Identifier: CC-BY-SA-4.0 AND LicenseRef-Patent-license

@startuml

!include psa-spec.pumh
!include psa-dataflow.pumh

skinparam RectangleborderThickness 0
skinparam RectanglefontColor white
skinparam DatabaseBorderColor #PSAMidGray
skinparam InterfaceBorderColor #PSAMidGray

left to right direction

dfd_tb("Device ") {
    rectangle "Application" as caller #PSAMidGray
    interface "**Secure Storage API**" as api  #PSAGreen
    dfd_tb($label="Platform Root of Trust") {
      rectangle "Storage service" as service #PSAMidBlue
    }
    dfd_tb($label="Replay-Protected\nMemory Block") {
      database "Storage medium" as store #PSALightGray
    }
}

caller -d- api
api -d-> service : DF1
service <-d-> store : DF4

@enduml
