' SPDX-FileCopyrightText: Copyright 2023 Arm Limited and/or its affiliates <open-source-office@arm.com>
' SPDX-License-Identifier: CC-BY-SA-4.0 AND LicenseRef-Patent-license

@startuml

!include atg-spec.pumh
!include atg-lifecycle.pumh

stakeholder "SiP and OEM" as n1
stakeholder "SiP and/or OEM" as n2
stakeholder "[everybody]" as n3
stakeholder_skip as n4
stakeholder "SiP, OEM,\nand Owner" as n5

lifecycle_phase "Manufacturing" as r1 {
   lifecycle_state "System\nmanufacturing\nand initialization" as lc1
   lifecycle_state "Provision of\nRoot of Trust\nsecrets" as lc2
}
lifecycle_phase "Operational" as r3 {
   lifecycle_state "Boot" as lc3
   lifecycle_state "Secure operation" as lc4
}
lifecycle_phase "End of life" as r5 {
   lifecycle_state "Return to\nManufacturer" as lc5
}

lc1 --> lc2
lc2 --> lc3
lc3 --> lc4
lc4 --> lc5

n1 -[hidden]- n2
n2 -[hidden]- n3
n3 -[hidden]- n4
n4 -[hidden]- n5

lc1 -[hidden] n1

@enduml
