' SPDX-FileCopyrightText: Copyright 2023 Arm Limited and/or its affiliates <open-source-office@arm.com>
' SPDX-License-Identifier: CC-BY-SA-4.0 AND LicenseRef-Patent-license

@startuml

!include atg-spec.pumh
!include atg-dataflow.pumh

skinparam rectangle {
    backgroundColor #ArmMidBlue
    borderColor darkred
    borderThickness 0
    fontColor white
}

skinparam card {
    backgroundColor #0091BD20
    borderColor #ArmMidBlue
    borderThickness 0
    fontColor black
}

left to right direction

note "SiP and OEM" as n1
note "SiP and/or OEM" as n2
note "[everybody]" as n3
label " " as n4
note "SiP, OEM,\nand Owner" as n5

card "Manufacturing" as r1 {
   rectangle "System\nmanufacturing\nand initialization" as lc1
   rectangle "Provision of\nRoot of Trust\nsecrets" as lc2
}
card "Operational" as r3 {
   rectangle "Boot" as lc3
   rectangle "Secure operation" as lc4
}
card "End of life" as r5 {
   rectangle "Return to\nManufacturer" as lc5
}

lc1 --> lc2
lc2 --> lc3
lc3 --> lc4
lc4 --> lc5

n1 -[hidden]- n2
n2 -[hidden]- n3
n3 -[hidden]- n4
n4 -[hidden]- n5

lc1 -[hidden] n1

@enduml
