' SPDX-FileCopyrightText: Copyright 2022 Arm Limited and/or its affiliates
' SPDX-License-Identifier: CC-BY-SA-4.0 AND LicenseRef-Patent-license

@startuml

!include psa-spec.pumh
!include psa-dataflow.pumh

skinparam RectangleborderThickness 0
skinparam RectanglefontColor white
skinparam DatabaseBorderColor #PSAMidGray
skinparam InterfaceBorderColor #PSAMidGray

rectangle "Firmware creator" as creator #PSADarkBlue
cloud Internet {
    rectangle "Update server" as server #PSAMidGray
}
interface "MQTT\n CoAP\nHTTPS\n    ..." as tls #PSALightGray

dfd_tb("Device ") {
    rectangle "Update client" as client #PSAMidGray
    interface "  **Firmware**\n**Update API**" as api  #PSAGreen
    rectangle "Update service" as service #PSAMidBlue
    database "Firmware store" as store #PSALightGray
    rectangle "Bootloader" as bootloader #PSAMidBlue
    label "<size:30>   <&key>\nTrust anchor" as anchor
}

database "External storage" as drive #PSALightGray
interface "USB" as usb #PSALightGray

creator -> server
server <- tls
tls -> client
client - api
api -> service
service --> store
service -[hidden]right-> bootloader
bootloader --> store
bootloader -> anchor

server -[hidden]down- drive
tls -[hidden]down- usb
drive <- usb
usb -[norank]-> client

@enduml
