' SPDX-FileCopyrightText: Copyright 2022 Arm Limited and/or its affiliates
' SPDX-License-Identifier: CC-BY-SA-4.0 AND LicenseRef-Patent-license

@startuml

!include psa-spec.pumh
!include psa-dataflow.pumh

skinparam RectangleborderThickness 0
skinparam RectanglefontColor white
skinparam FilefontColor white
skinparam DatabaseBorderColor #PSAMidGray
skinparam InterfaceBorderColor #PSAMidGray

file "Firmware package" <<data>> as firmware #PSADarkBlue

dfd_tb($label = "Device") {
    dfd_align() {
        rectangle "Update client" <<app>> as client #PSAMidGray
        interface "  **Firmware**\n**Update API**" as api  #PSAGreen
        rectangle "Update service" <<library>> as service #PSAMidBlue
        database "Staging area" as second #PSALightGray
    }
    dfd_tb($label = "Platform Root of Trust") {
        database "//active// image" as active #PSALightGray
        rectangle "Bootloader" as bootloader #PSAMidBlue
        label "<size:30>   <&key>\nTrust anchor" as anchor
    }
}

firmware -> client
client - api
api -> service
service --> second
bootloader -[norank]-> second
bootloader --> active
bootloader -> anchor

@enduml
