' SPDX-FileCopyrightText: Copyright 2022 Arm Limited and/or its affiliates <open-source-office@arm.com>
' SPDX-License-Identifier: CC-BY-SA-4.0 AND LicenseRef-Patent-license

@startuml

!include atg-spec.pumh
!include atg-dataflow.pumh

skinparam RectangleborderThickness 0
skinparam RectanglefontColor white
skinparam FilefontColor white
skinparam DatabaseBorderColor #ArmMidGray
skinparam InterfaceBorderColor #ArmMidGray

file "Firmware package" <<data>> as firmware #ArmDarkBlue

dfd_tb($label = "Device") {
    dfd_align() {
        rectangle "Update client" <<app>> as client #ArmMidGray
        interface "  **Firmware**\n**Update API**" as api  #ArmGreen
        rectangle "Update service" <<library>> as service #ArmMidBlue
        database "Staging area" as second #ArmLightGray
    }
    dfd_tb($label = "Platform Root of Trust") {
        database "//active// image" as active #ArmLightGray
        rectangle "Bootloader" as bootloader #ArmMidBlue
        label "<size:30>   <&key>\nTrust anchor" as anchor
    }
}

firmware -> client
client - api
api -> service
service --> second
bootloader -[norank]-> second
bootloader --> active
bootloader -> anchor

@enduml
