' SPDX-FileCopyrightText: Copyright 2024 Arm Limited and/or its affiliates <open-source-office@arm.com>
' SPDX-License-Identifier: CC-BY-SA-4.0 AND LicenseRef-Patent-license

@startuml

!include atg-spec.pumh

' Complex SUIT installation using the FWU API, no boot

box Network
participant "Update server" as server
end box
box Device
participant "Update client" as client
participant "Firmware Update API" as api
participant "Update service" as service
end box
entity "Envelope state" as envelope
entity "Payload state" as payload

autonumber
activate client
activate envelope #LightBlue
rnote over envelope #LightBlue: READY

client -> service: ""psa_fwu_start(envelope_id)""
note left: Transfer SUIT Envelope
deactivate envelope
activate service #ddd
return ""PSA_SUCCESS""
deactivate service
activate envelope #PaleGreen
rnote over envelope #PaleGreen: WRITING

client -> service #ddd: ""psa_fwu_write(envelope_id, ...)""
activate service #ddd
return ""PSA_SUCCESS""
deactivate service

client -> service: ""psa_fwu_finish(envelope_id)""
deactivate envelope
activate service #ddd
return ""PSA_FWU_PROCESSING_REQUIRED""
deactivate service
activate envelope #PaleGoldenRod
rnote over envelope #PaleGoldenRod: PROCESSING

client -> service: ""psa_fwu_process()""
note left: Process SUIT manifest
note over service
    Verify manifest
    ""suit-payload-fetch ""sequence
end note
deactivate envelope
activate service #ddd

loop While additional payloads are required
    note over server, service: Transfer\npayload(s)
end
autonumber 21
client <-- service: ""PSA_SUCCESS""
note left: Manifest processing complete
deactivate service
activate envelope #LightSalmon
rnote over envelope #LightSalmon: CANDIDATE

client -> service #ddd: ""psa_fwu_install()""
note left: Proceed with installation
deactivate envelope
activate service #ddd

return ""PSA_FWU_PROCESSING_REQUIRED""
deactivate service
activate envelope #PaleGoldenRod
rnote over envelope #PaleGoldenRod: PROCESSING

client -> service: ""psa_fwu_process()""
note left: Process SUIT commands
note over service: ""suit-install ""sequence
deactivate envelope
activate service #ddd

loop While additional payloads are required
    note over server, service: Transfer\npayload(s)
end
note over service
    ""suit-validate ""sequence
    ""suit-load ""sequence
    ""suit-invoke ""sequence
end note
autonumber 38
client <-- service: ""PSA_SUCCESS""
deactivate service
activate envelope #aad
rnote over envelope #aad: UPDATED

@enduml
