' SPDX-FileCopyrightText: Copyright 2022 Arm Limited and/or its affiliates
' SPDX-License-Identifier: CC-BY-SA-4.0 AND LicenseRef-Patent-license

@startuml

!include psa-spec.pumh
!include psa-dataflow.pumh

skinparam RectangleborderThickness 0
skinparam RectanglefontColor white
skinparam DatabaseBorderColor #PSAMidGray
skinparam InterfaceBorderColor #PSAMidGray

rectangle "Firmware creator" as creator #PSADarkBlue
cloud Internet {
    rectangle "Update server" as server #PSAMidGray
}
interface "MQTT\n CoAP\nHTTPS\n     ..." as tls #PSALightGray

dfd_tb("Device ") {
    rectangle "Update client" as client #PSAMidBlue
    database "Firmware store" as store #PSALightGray
}

creator -> server
tls -left-> server
tls -right-> client
client --> store

@enduml
