' SPDX-FileCopyrightText: Copyright 2023 Arm Limited and/or its affiliates <open-source-office@arm.com>
' SPDX-License-Identifier: CC-BY-SA-4.0 AND LicenseRef-Patent-license

@startuml

!include atg-spec.pumh
!include atg-lifecycle.pumh

stakeholder "SiP and OEM" as k1
stakeholder "SiP, OEM,\nand/or Owner" as k2
stakeholder "[everybody]" as k3
stakeholder_skip as k4
stakeholder_skip as k5
stakeholder "SiP, OEM,\nand Owner" as k6

lifecycle_phase "Manufacturing" as p1{
    lifecycle_state "System\nmanufacturing\nand initialization" as s1
    lifecycle_state "Provision of\nauthorization\ncredentials" as s2
}
lifecycle_phase "Operation" as p3 {
   lifecycle_state "Boot\n(Install update)" as s3
   lifecycle_state "Operation\n(Prepare update)" as s4
   lifecycle_state "Reset" as s5
}
lifecycle_phase "End of life" as p6 {
   lifecycle_state "Return to\nManufacturer" as s6
}

k1 -[hidden]l- s1

s1 --> s2
s2 --> s3
s3 --> s4
s4 --> s5
s3 <-- s5
s5 --> s6

k1 -[hidden]- k2
k2 -[hidden]- k3
k3 -[hidden]- k4
k4 -[hidden]- k5
k5 -[hidden]- k6

@enduml
